//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vedrana
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<evidencijaNjege> evidencijaNjeges { get; set; }
        public virtual DbSet<imaUslugu> imaUslugus { get; set; }
        public virtual DbSet<jelo> jeloes { get; set; }
        public virtual DbSet<jelovnik> jelovniks { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<koristiProizvod> koristiProizvods { get; set; }
        public virtual DbSet<osoba> osobas { get; set; }
        public virtual DbSet<seNalazi> seNalazis { get; set; }
        public virtual DbSet<seSastoji> seSastojis { get; set; }
        public virtual DbSet<soba> sobas { get; set; }
        public virtual DbSet<usluga> uslugas { get; set; }
        public virtual DbSet<zaposlenik> zaposleniks { get; set; }
        public virtual DbSet<narudzba> narudzbas { get; set; }
        public virtual DbSet<proizvod> proizvods { get; set; }
        public virtual DbSet<seNarucuje> seNarucujes { get; set; }
    }
}
