//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vedrana
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencijaNjege
    {
        public string oib { get; set; }
        public int imaUsluguId { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string napomena { get; set; }
        public int evidencijaNjegeID { get; set; }
    
        public virtual imaUslugu imaUslugu { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
    }
}
