//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vedrana
{
    using System;
    using System.Collections.Generic;
    
    public partial class imaUslugu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public imaUslugu()
        {
            this.evidencijaNjeges = new HashSet<evidencijaNjege>();
        }
    
        public int imaUsluguId { get; set; }
        public string oib { get; set; }
        public int uslugaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencijaNjege> evidencijaNjeges { get; set; }
        public virtual korisnik korisnik { get; set; }
        public virtual usluga usluga { get; set; }
    }
}
