//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vedrana
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoba
    {
        public string oib { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string adresa { get; set; }
        public string kontakt { get; set; }
        public Nullable<System.DateTime> datumRodjenja { get; set; }
        public Nullable<System.DateTime> datumPocetka { get; set; }
        public Nullable<System.DateTime> datumZavrsetka { get; set; }
        public Nullable<byte> koronaPozitivan { get; set; }
    
        public virtual korisnik korisnik { get; set; }
    }
}
