//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vedrana
{
    using System;
    using System.Collections.Generic;
    
    public partial class seNalazi
    {
        public int jeloId { get; set; }
        public int jelovnikId { get; set; }
        public int seNalaziID { get; set; }
    
        public virtual jelo jelo { get; set; }
        public virtual jelovnik jelovnik { get; set; }
    }
}
