//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vedrana
{
    using System;
    using System.Collections.Generic;
    
    public partial class usluga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usluga()
        {
            this.imaUslugus = new HashSet<imaUslugu>();
            this.koristiProizvods = new HashSet<koristiProizvod>();
        }
    
        public int uslugaId { get; set; }
        public string naziv { get; set; }
        public Nullable<double> cijena { get; set; }
        public string opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imaUslugu> imaUslugus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<koristiProizvod> koristiProizvods { get; set; }
    }
}
